languageCode = "en"
languageName = "English"
weight = 1
title = "Jasmeet Singh"

[params]
  displayName = "Jasmeet Singh"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/transparent_ai_profile.png"
  secondaryLogo = "img/transparent_ai_profile.png"
  description = "Robotics Engineer | Engineering Motion, Simulating Reality."
  copyright = "Copyright © { year } Jasmeet Singh"

[params.author]
  name = "Jasmeet Singh"
  email = "jasmeet0915@gmail.com"
  image = "img/profile_photo.jpg"
  headline = "Robotics Engineer | Engineering Motion, Simulating Reality."
  bio = "Robotics Engineer | Engineering Motion, Simulating Reality."
  links = [
    { github = "https://github.com/jasmeet0915" },
    { linkedin = "https://www.linkedin.com/in/jasmeetsingh2911/"},
    { instagram = "https://www.instagram.com/debounsingh/"},
    { youtube = "https://www.youtube.com/@processingh"},
    { x-twitter = "https://x.com/debounSingh" }
  ]